name: CI

on: [push]

jobs:
  build:
    # docker executor
    runs-on: ubuntu-latest

    container:
      image: debian:buster-slim
      env:
        DEBIAN_FRONTEND: noninteractive

    steps:
    - uses: actions/checkout@v1

    - name: Install build dependencies for Linux daemon 'callblockerd'
      run: |
        apt-get update
        apt-get install --no-install-recommends -y \
          dpkg-dev pkg-config \
          ninja-build g++ \
          libjson-c-dev libphonenumber-dev uuid-dev libssl-dev \
          python3 python3-bs4 python3-ldif3 python3-vobject \
          python3-pip python3-setuptools
        pip3 install meson

    - name: Install build dependencies for Web interface
      run: |
        apt-get install --no-install-recommends -y \
          wget
        wget -qO- https://deb.nodesource.com/setup_12.x | bash -
        apt-get update
        apt-get install --no-install-recommends -y \
          nodejs

    - name: Build all
      run: |
        /usr/local/bin/meson --prefix=/usr --sysconfdir=/etc --localstatedir=/usr/var build
        cd build && ninja

    - name: Unit test
      run: |
        cd build && ninja test

    - name: Release
      run: |
        cd build && ninja install

